require './statemachine.test'
require 'app/react/test'
require 'app/flux/test'
require './applicationmanager.test'
# require './searchcontroller.test'
require './kodinglistcontroller.test'
require './kodinglistview.test'
require './environmentlistcontroller.test'
require './commonviews/bannernotificationview.test'
require './util/stripHTMLtoText.test'
require './util/proxifier.test'
require './stacktemplatelistcontroller.test'
require 'app/components/codeblock/test'
